// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFrHgJY1mL3fh5hpzhbBj4TVg_S7wJN9Q',
    appId: '1:316798941408:web:f9159abcc7c308a0537885',
    messagingSenderId: '316798941408',
    projectId: 'tapajosweb-transporte',
    authDomain: 'tapajosweb-transporte.firebaseapp.com',
    storageBucket: 'tapajosweb-transporte.firebasestorage.app',
    measurementId: 'G-EV0BR85YR0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8ix_qsDbdkh2SXzV6pS6_JQYcAXaR75A',
    appId: '1:316798941408:android:2b8468ee6b8ceb55537885',
    messagingSenderId: '316798941408',
    projectId: 'tapajosweb-transporte',
    storageBucket: 'tapajosweb-transporte.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaYnA7Gz_Udffa9amXAGtwjKnUkQ0GjYI',
    appId: '1:316798941408:ios:176bb742587a7d72537885',
    messagingSenderId: '316798941408',
    projectId: 'tapajosweb-transporte',
    storageBucket: 'tapajosweb-transporte.firebasestorage.app',
    iosBundleId: 'com.tapajosweb.gorideDriver',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaYnA7Gz_Udffa9amXAGtwjKnUkQ0GjYI',
    appId: '1:316798941408:ios:176bb742587a7d72537885',
    messagingSenderId: '316798941408',
    projectId: 'tapajosweb-transporte',
    storageBucket: 'tapajosweb-transporte.firebasestorage.app',
    iosBundleId: 'com.tapajosweb.gorideDriver',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFrHgJY1mL3fh5hpzhbBj4TVg_S7wJN9Q',
    appId: '1:316798941408:web:bbf6f2824132d9b7537885',
    messagingSenderId: '316798941408',
    projectId: 'tapajosweb-transporte',
    authDomain: 'tapajosweb-transporte.firebaseapp.com',
    storageBucket: 'tapajosweb-transporte.firebasestorage.app',
    measurementId: 'G-CZRLL09NGE',
  );
}
